# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The APT Package Management system uses a data-rich caching '
#' structure. This accessor function returns the names of installable
#' packages.
#' @title Retrieve Names of All Installable Packages
#' @return A data frame with two columns containing the 
#' package name, and the installed version or NA if not installed
#' @author Dirk Eddelbuettel
getPackages <- function() {
    .Call('rapt_getPackages', PACKAGE = 'rapt')
}

